
name: Release python package

on:
  push:
    branches:
      - master

jobs:
  test-and-lint:
      uses: ./.github/workflows/test-and-lint.yml
  tag-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
