name: Test and Lint Superglue

on:
  workflow_call:


jobs:
  test-and-lint:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Superglue and development dependencies
        run: make install-dev

      - name: Run Black Linter
        run: make lint

      - name: Run Pytest
        run: make test
